version: '3.5'

services:
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:7.0.0
    ports:
      - 8180:8080
    env_file:
      - environment-dev.env
    networks:
      - keycloak-network
    volumes:
      - ./scripts:/opt/jboss/scripts/
      - ./themes/mytheme/:/opt/jboss/keycloak/themes/mytheme/

networks:
  keycloak-network:
    name: keycloak-network
    driver: bridge
